# Choose the Image which has Node installed already
FROM node:12

# COPY all the files from Current Directory into the Container
COPY ./ ./

# Install the Project Dependencies like Express Framework
RUN npm install

# Tell that this image is going to Open a Port 
EXPOSE 8084

# Default Command to launch the Application
CMD ["node" , "app.js"]


#docker run -p 8084:3000 -t docker-test